/*
Copyright (c) 2019 Ferhat Kurtulmuş
Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:
The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module opencvd.contrib.xfeatures2d;

import opencvd.cvcore;

private extern (C){
    SIFT SIFT_Create();
    void SIFT_Close(SIFT f);
    KeyPoints SIFT_Detect(SIFT f, Mat src);
    KeyPoints SIFT_DetectAndCompute(SIFT f, Mat src, Mat mask, Mat desc);

    SURF SURF_Create();
    void SURF_Close(SURF f);
    KeyPoints SURF_Detect(SURF f, Mat src);
    KeyPoints SURF_DetectAndCompute(SURF f, Mat src, Mat mask, Mat desc);
    SURF SURF_CreateWithParams(double hessianThreshold, int nOctaves, int nOctaveLayers, bool extended, bool upright);
    bool SURF_GetExtended(SURF s);
    double SURF_GetHessianThreshold(SURF s);
    int SURF_GetNOctaveLayers(SURF s);
    int SURF_GetNOctaves(SURF s);
    bool SURF_GetUpright(SURF s);
    void SURF_SetExtended(SURF s, bool extended);
    void SURF_SetHessianThreshold (SURF s, double hessianThreshold);
    void SURF_SetNOctaveLayers (SURF s, int nOctaveLayers);
    void SURF_SetNOctaves (SURF s, int nOctaves);
    void SURF_SetUpright (SURF s, bool upright);
    KeyPoints SURF_DetectAndCompute2(SURF s, Mat image, Mat mask, Mat descriptors, bool useProvidedKeypoints);
}

struct SIFT {
    void* p;
    
    void close(){
        SIFT_Close(this);
    }
    
    static SIFT opCall(){
        return SIFT_Create();
    }
    
    KeyPoint[] detect(Mat src){
        KeyPoints kpts = SIFT_Detect(this, src);
        KeyPoint[] ret = kpts.keypoints[0..kpts.length].dup;
        KeyPoints_Close(kpts);
        return ret;
    }
    
    KeyPoint[] detectAndCompute(Mat src, Mat mask, Mat desc){
        KeyPoints kpts = SIFT_DetectAndCompute(this, src, mask, desc);
        KeyPoint[] ret = kpts.keypoints[0..kpts.length].dup;
        KeyPoints_Close(kpts);
        return ret;
    }
}

SIFT newSIFT(){
    return SIFT_Create();
}

void Destroy(SIFT s){
    SIFT_Close(s);
}

struct SURF {
    void* p;
    
    void close(){
        SURF_Close(this);
    }
    
    static SURF opCall(){
        return SURF_Create();
    }
    
    static SURF opCall(double hessianThreshold=100, int nOctaves=4, int nOctaveLayers=3, bool extended=false, bool upright=false){
        return SURF_CreateWithParams(hessianThreshold, nOctaves, nOctaveLayers, extended, upright);
    }
    
    bool getExtended(){
        return SURF_GetExtended(this);
    }
    
    double getHessianThreshold(){
        return SURF_GetHessianThreshold(this);
    }
    
    int getNOctaveLayers(){
        return SURF_GetNOctaveLayers(this);
    }
    
    int getNOctaves(){
        return SURF_GetNOctaves(this);
    }
    
    bool getUpright(){
        return SURF_GetUpright(this);
    }
    
    void setExtended(bool extended){
        SURF_SetExtended(this, extended);
    }
    
    void setHessianThreshold (double hessianThreshold){
        SURF_SetHessianThreshold (this, hessianThreshold);
    }
    
    void setNOctaveLayers (int nOctaveLayers){
        SURF_SetNOctaveLayers (this, nOctaveLayers);
    }
    
    void setNOctaves (int nOctaves){
        SURF_SetNOctaves (this, nOctaves);
    }
    
    void setUpright (bool upright){
        SURF_SetUpright (this, upright);
    }
    
    KeyPoint[] detect(Mat src){
        KeyPoints kpts = SURF_Detect(this, src);
        KeyPoint[] ret = kpts.keypoints[0..kpts.length].dup;
        KeyPoints_Close(kpts);
        return ret;
    }
    
    KeyPoint[] detectAndCompute(Mat src, Mat mask, Mat desc, bool useProvidedKeypoints = false){
        KeyPoints kpts = SURF_DetectAndCompute2(this, src, mask, desc, useProvidedKeypoints);
        KeyPoint[] ret = kpts.keypoints[0..kpts.length].dup;
        KeyPoints_Close(kpts);
        return ret;
    }
}

void Destroy(SURF s){
    SURF_Close(s);
}
