/*
Copyright (c) 2019 Ferhat Kurtulmuş
Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:
The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module opencvd.imgcodecs;

import std.string;

import opencvd.cvcore;

private {
    extern (C){
        Mat Image_IMRead(const char* filename, int flags);
        bool Image_IMWrite(const char* filename, Mat img);
        bool Image_IMWrite_WithParams(const char* filename, Mat img, IntVector params);
        ByteArray Image_IMEncode(const char* fileExt, Mat img);
        ByteArray Image_IMEncode_WithParams(const char* fileExt, Mat img, IntVector params);
        Mat Image_IMDecode(ByteArray buf, int flags);
    }
}

enum: int { // cv::ImreadModes
    IMREAD_UNCHANGED = -1, 
    IMREAD_GRAYSCALE = 0, 
    IMREAD_COLOR = 1, 
    IMREAD_ANYDEPTH = 2, 
    IMREAD_ANYCOLOR = 4, 
    IMREAD_LOAD_GDAL = 8, 
    IMREAD_REDUCED_GRAYSCALE_2 = 16, 
    IMREAD_REDUCED_COLOR_2 = 17, 
    IMREAD_REDUCED_GRAYSCALE_4 = 32, 
    IMREAD_REDUCED_COLOR_4 = 33, 
    IMREAD_REDUCED_GRAYSCALE_8 = 64, 
    IMREAD_REDUCED_COLOR_8 = 65, 
    IMREAD_IGNORE_ORIENTATION = 128 
}

Mat imread(string filename, int flags = IMREAD_UNCHANGED){
    return Image_IMRead(toStringz(filename), flags);
}

bool imwrite(string filename, Mat img){
    return Image_IMWrite(toStringz(filename), img);
}

bool imwriteWithParams(string filename, Mat img, IntVector params){
    return Image_IMWrite_WithParams(toStringz(filename), img, params);
}

ByteArray imencode(string fileExt, Mat img){
    return Image_IMEncode(toStringz(fileExt), img);
}

ByteArray imencodeWithParams(string fileExt, Mat img, IntVector params){
    return Image_IMEncode_WithParams(toStringz(fileExt), img, params);
}

Mat imdecode(ByteArray buf, int flags){
    return Image_IMDecode(buf, flags);
}

