/*
Copyright (c) 2019 Ferhat Kurtulmuş
Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:
The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module opencvd.stitching;

import std.conv;

import opencvd.cvcore;

private extern (C) {
    void Stitcher_Close(Stitcher st);
    Stitcher Stitcher_Create(int mode);
    int Stitcher_Stitch(Stitcher st, Mats images, Mat pano);
}

struct Stitcher {
    void* p;
    
    enum: int{
        PANORAMA = 0,
        SCANS = 1
    }
    
    enum: int{
        OK = 0,
        ERR_NEED_MORE_IMGS = 1,
        ERR_HOMOGRAPHY_EST_FAIL = 2,
        ERR_CAMERA_PARAMS_ADJUST_FAIL = 3
    }
    
    static Stitcher create(int mode=Stitcher.PANORAMA){
        return Stitcher_Create(mode);
    }
    
    static Stitcher opCall(int mode=Stitcher.PANORAMA){
        return Stitcher_Create(mode);
    }
    
    int stitch(Mat[] images, Mat pano){
        Mats imgs = {images.ptr, images.length.to!int};
        
        return Stitcher_Stitch(this, imgs, pano);
    }
}

void Destroy(Stitcher st){
    Stitcher_Close(st);
}
